//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTR_App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRISM-SERVER\\BMICONNECT;Initial Catalog=MTR_Database;Integrated Secur" +
            "ity=False;User ID=Sa;Password=BMI5q1d8#;Connect Timeout=15;Encrypt=False;TrustSe" +
            "rverCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string MTR_DatabaseConn {
            get {
                return ((string)(this["MTR_DatabaseConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRISM-SERVER\\BMICONNECT;Initial Catalog=MTRInfoTables;Integrated Secu" +
            "rity=False;User ID=Sa;Password=BMI5q1d8#;Connect Timeout=15;Encrypt=False;TrustS" +
            "erverCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string MTRInfoTablesConn {
            get {
                return ((string)(this["MTRInfoTablesConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRISM-SERVER\\BMICONNECT;Initial Catalog=Credentials;Integrated Securi" +
            "ty=False;User ID=Sa;Password=BMI5q1d8#;Connect Timeout=15;Encrypt=False;TrustSer" +
            "verCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string Credentials {
            get {
                return ((string)(this["Credentials"]));
            }
        }
    }
}
